#pragma once
#include <string>
#include <vector>

static std::vector<std::string> dodgeSkills = {
	"FizzPiercingStrike",
	"UFSlash",
	"HungeringStrike",
	"YasuoDash",
	"KatarinaRTrigger",
	"KatarinaE",
	"DariusR",
	"GarenQ",
	"GarenR",
	"IreliaE",
	"LeeSinR",
	"OlafE",
	"RenektonW",
	"RenektonPreExecute",
	"RengarQ",
	"VeigarR",
	"VolibearW",
	"XenZhaoThrust3",
	"TwitchEParticle",
	"MonkeyKingSpinToWin",
	"RengarPassiveBuffDash",
	"TalonCutthroat",
	"CurseoftheSadMummy",
	"EnchantedCrystalArrow",
	"RocketGrab",
	"EliseHumanE",
	"GragasE",
	"GravesChargeShot",
	"JhinRShot",
	"LeonaZenithBlade",
	"LeonaSolarFlare",
	"DarkBindingMissile",
	"OlafAxeThrowCast",
	"OrianaDetonateCommand-",
	"RumbleCarpetBombM",
	"SejuaniGlacialPrisonStart",
	"SonaR",
	"ThreshQ",
	"Vi-q",
	"xerathrmissilewrapper",
	"ZyraE"
	};
